### ISSUE TITLE
Error on init react native app with new version

### ISSUE THREAD

**Issue by taipa-ibl** [thecodingmachine/react-native-boilerplate#118]
`yarn remove v1.22.4
[1/2] 🗑  Removing module react-native-template-@thecodingmachine/react-native-boilerplate...
error This module isn't specified in a package.json file.
info Visit https://yarnpkg.com/en/docs/cli/remove for documentation about this command.
warn Failed to clean up template temp files in node_modules/react-native-template-@thecodingmachine/react-native-boilerplate. This is not a critical error, you can work on your app.
(node:70598) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, lstat '/Users/taipa/develop/bombi-dev/MyApp/node_modules/react-native-template-@thecodingmachine/react-native-boilerplate'
    at Object.lstatSync (fs.js:845:3)
    at walk (/Users/taipa/develop/bombi-dev/MyApp/node_modules/@react-native-community/cli/build/tools/walk.js:38:22)
    at copyProjectTemplateAndReplace (/Users/taipa/develop/bombi-dev/MyApp/node_modules/@react-native-community/cli/build/tools/generator/copyProjectTemplateAndReplace.js:83:21)
    at createFromRemoteTemplate (/Users/taipa/develop/bombi-dev/MyApp/node_modules/@react-native-community/cli/build/tools/generator/templates.js:121:48)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:70598) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:70598) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by JeremyDolle** [comment]
Hello, when this append ? When you launch `npx react-native init MyApp --template @thecodingmachine/react-native-boilerplate` ? in what step this append ?

**Comment by taipa-ibl** [comment]
Hello @JeremyDolle 
Yep, this error happens right on the command `npx react-native init MyApp --template @thecodingmachine/react-native-boilerplate`.

**Comment by taipa-ibl** [comment]
Hello @JeremyDolle 
This error was resolved after I upgrade node from v10.16.3 to v15.0.1.

Best regards,

**Comment by JeremyDolle** [comment]
Ok thanks for the update, I close the issue
