### ISSUE TITLE
src folder not created in windows 10, node 10/12/14/15

### ISSUE THREAD

**Issue by rajeshd50** [thecodingmachine/react-native-boilerplate#128]
Hello, 

First of all thanks for this awesome boilerplate, I've build some apps using the old version of this boilerplate, now I wanted to try the v2. I'm using windows OS with all requirements fulfilled. 

After running the init code 
`npx react-native init MyApp --template @thecodingmachine/react-native-boilerplate`
I got the following error

`yarn remove v1.22.5
[1/2] Removing module react-native-template-@thecodingmachine/react-native-boilerplate...
error This module isn't specified in a package.json file.
info Visit https://yarnpkg.com/en/docs/cli/remove for documentation about this command.
warn Failed to clean up template temp files in node_modules/react-native-template-@thecodingmachine/react-native-boilerplate. This is not a critical error, you can work on your app.
(node:26932) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, lstat 'D:\Projects\mobile\MyApp\node_modules\react-native-template-@thecodingmachine\react-native-boilerplate'
    at Object.lstatSync (fs.js:1007:3)
    at walk (D:\Projects\mobile\MyApp\node_modules\@react-native-community\cli\build\tools\walk.js:38:22)
    at copyProjectTemplateAndReplace (D:\Projects\mobile\MyApp\node_modules\@react-native-community\cli\build\tools\generator\copyProjectTemplateAndReplace.js:83:21)
    at createFromRemoteTemplate (D:\Projects\mobile\MyApp\node_modules\@react-native-community\cli\build\tools\generator\templates.js:121:48)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async createProjectFromTemplate (D:\Projects\mobile\MyApp\node_modules\@react-native-community\cli\build\tools\generator\templates.js:88:3)
    at async generateProject (D:\Projects\mobile\MyApp\node_modules\@react-native-community\cli\build\commands\init\initCompat.js:118:3)
    at async Object.initCompat (D:\Projects\mobile\MyApp\node_modules\@react-native-community\cli\build\commands\init\initCompat.js:105:3)
(node:26932) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:26932) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**The issue is not only this (as I've checked other issue posted for this), I'm not getting src folder in my newly created app directory**.. check the image 

![output](https://user-images.githubusercontent.com/8902274/98558556-95b05980-22cb-11eb-8c04-cac34d5ab3b9.png)

**I'm using nvm, and used different versions of node same result every time..**

Can you please check and let me know if I'm missing something!

Thanks a lot :)

**Comment by AurelGit** [comment]
Hey @rajeshd50 and thanks for your message :) 

This issue could come from an old version of the `cli` globally installed on your computer.

The RN documentation explain : 
```
If you previously installed a global react-native-cli package, please remove it as it may cause unexpected issues.
```

Could you try to remove the global `react-native-cli` package if installed ?

If not, we have to dig more about your problem !

**Comment by AurelGit** [comment]
You can also take a loot at : https://github.com/thecodingmachine/react-native-boilerplate/issues/118

**Comment by rajeshd50** [comment]
Hi @AurelGit 

Thanks for your suggestions, I looked into the both issues you have tagged, but no success. Please check the followings

> global npm packages

```
PS D:\Projects\mobile> npm list -g --depth 0
C:\Program Files\nodejs
-- npm@6.14.6
PS D:\Projects\mobile>
```


> global yarn packages

```
PS D:\Projects\mobile> yarn global list
yarn global v1.22.5
info "@adonisjs/cli@4.0.12" has binaries:
   - adonis
info "@nestjs/cli@7.5.1" has binaries:
   - nest
info "firebase-tools@8.7.0" has binaries:
   - firebase
info "ignite-cli@3.5.1" has binaries:
   - ignite
info "lad@1.0.13" has binaries:
   - lad
info "react-devtools@4.6.0" has binaries:
   - react-devtools
info "serve@11.3.2" has binaries:
   - serve
Done in 1.67s.
PS D:\Projects\mobile>
```

I've tried both after installing/uninstalling global react-native-cli. but same thing happening

**Comment by JeremyDolle** [comment]
can you give us your npx version, your node version and what happen if you run `react-native -v` or `react-native-cli -v` ?

**Comment by rajeshd50** [comment]
it's react-native-cli: 2.0.1

**Comment by rajeshd50** [comment]
PS D:\Projects\mobile> node -v
v12.18.3
PS D:\Projects\mobile> npm -v
6.14.6
PS D:\Projects\mobile>

**Comment by rajeshd50** [comment]
PS D:\Projects\mobile> nvm list

    15.1.0
    14.15.0
  * 12.18.3 (Currently using 64-bit executable)
    10.15.3
    8.17.0
PS D:\Projects\mobile>

I've tried using above node versions

**Comment by rajeshd50** [comment]
Hey @AurelGit @JeremyDolle got it working, the issue was with using **nvm** I had react-native-cli installed with a different version of node, I uninstalled react-native-cli from that specific version and now it got fixed. Thanks for your help :)
