### ISSUE TITLE
Installation not working

### ISSUE THREAD

**Issue by fredyonge** [thecodingmachine/react-native-boilerplate#190]
Bonjour mes amis francaise!
I saw your template and it looked great! Unfortunatley I encountered a bug.

**Describe the bug**
I am running the command but the installation with the template is not working.

**To Reproduce**
1. Run Installation
2. Problem

**Expected behavior**
I expect the installation to work properly

**Desktop (please complete the following information):**
 - OS: MacOS

**Additional context**
Note i installed react native projects prior
I cannot choose typescript either

Error: 
Error: 1/2] 🗑  Removing module react-native-template-@thecodingmachine/react-native-boilerplate...
error This module isn't specified in a package.json file.
info Visit https://yarnpkg.com/en/docs/cli/remove for documentation about this command.
warn Failed to clean up template temp files in node_modules/react-native-template-@thecodingmachine/react-native-boilerplate. This is not a critical error, you can work on your app.
(node:64770) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, lstat '/Users//Apps/MyApp/node_modules/react-native-template-@thecodingmachine/react-native-boilerplate'
    at Object.lstatSync (fs.js:1007:3)
    at walk (/Users/Apps/MyApp/node_modules/@react-native-community/cli/build/tools/walk.js:38:22)
    at copyProjectTemplateAndReplace (/UserApps/MyApp/node_modules/@react-native-community/cli/build/tools/generator/copyProjectTemplateAndReplace.js:83:21)
    at createFromRemoteTemplate (/Users/Apps/MyApp/node_modules/@react-native-community/cli/build/tools/generator/templates.js:121:48)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async createProjectFromTemplate (/User/Apps/MyApp/node_modules/@react-native-community/cli/build/tools/generator/templates.js:88:3)
    at async generateProject (/UsersApps/MyApp/node_modules/@react-native-community/cli/build/commands/init/initCompat.js:118:3)
    at async Object.initCompat (/UsersApps/MyApp/node_modules/@react-native-community/cli/build/commands/init/initCompat.js:105:3)
(node:64770) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:64770) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by JeremyDolle** [comment]
Bonjour @fredyonge ! 🇫🇷

See [#145](https://github.com/thecodingmachine/react-native-boilerplate/issues/145)
You probably have react-native-cli installed globally. Remove it as it said in the react-native [documentation](https://reactnative.dev/docs/environment-setup)
![image](https://user-images.githubusercontent.com/15814069/116141653-40310300-a6d9-11eb-9a8d-01262f1acf18.png)
let me know ! 😊

**Comment by fredyonge** [comment]
Works! Thank's that was fast! I thought because I was using npx, it should be working.
Now it's time to wrap my head around everything :)
