### ISSUE TITLE
Problems with installation

### ISSUE THREAD

**Issue by SomTambe** [thecodingmachine/react-native-boilerplate#244]
I ran the command `npx react-native init MyApp --template @thecodingmachine/react-native-boilerplate`, and then I navigated to the directory `MyApp`. Now after running `npm install` in the directory, I tried to build the project using `react-native run-android`, and I am now getting dependency errors it seems - 
```
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
(node:4356) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Jetifier found 998 file(s) to forward-jetify. Using 12 workers...
info JS server already running.
info Installing the app...

> Configure project :react-native-flipper
WARNING:: API 'variant.getJavaCompile()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'.
It will be removed in version 7.0 of the Android Gradle plugin.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getJavaCompile(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
WARNING:: Please remove usages of `jcenter()` Maven repository from your build scripts and migrate your build to other Maven repositories.
This repository is deprecated and it will be shut down in the future.
See http://developer.android.com/r/tools/jcenter-end-of-service for more information.
Currently detected usages in: project ':react-native-flipper', project ':react-native-masked-view_masked-view', project ':react-native-screens'

> Task :react-native-async-storage_async-storage:compileDebugJavaWithJavac

> Task :react-native-gesture-handler:compileDebugJavaWithJavac

> Task :react-native-safe-area-context:compileDebugJavaWithJavac

> Task :app:checkDebugDuplicateClasses FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9/userguide/command_line_interface.html#sec:command_line_warnings
99 actionable tasks: 85 executed, 14 up-to-date
Note: /home/somvt/onepoint/templates/OnePoint/node_modules/@react-native-async-storage/async-storage/android/src/main/java/com/reactnativecommunity/asyncstorage/AsyncStorageModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/somvt/onepoint/templates/OnePoint/node_modules/@react-native-async-storage/async-storage/android/src/main/java/com/reactnativecommunity/asyncstorage/AsyncStoragePackage.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class com.facebook.jni.CppException found in modules jetified-fbjni-0.2.2-runtime (com.facebook.fbjni:fbjni:0.2.2) and jetified-fbjni-java-only-0.2 (com.facebook.fbjni:fbjni-java-only:0.2.2)
     Duplicate class com.facebook.jni.CppSystemErrorException found in modules jetified-fbjni-0.2.2-runtime (com.facebook.fbjni:fbjni:0.2.2) and jetified-fbjni-java-only-0.2 (com.facebook.fbjni:fbjni-java-only:0.2.2)
     Duplicate class com.facebook.jni.DestructorThread found in modules jetified-fbjni-0.2.2-runtime (com.facebook.fbjni:fbjni:0.2.2) and jetified-fbjni-java-only-0.2 (com.facebook.fbjni:fbjni-java-only:0.2.2)
     Duplicate class com.facebook.jni.DestructorThread$1 found in modules jetified-fbjni-0.2.2-runtime (com.facebook.fbjni:fbjni:0.2.2) and jetified-fbjni-java-only-0.2 (com.facebook.fbjni:fbjni-java-only:0.2.2)
     Duplicate class com.facebook.jni.DestructorThread$Destructor found in modules jetified-fbjni-0.2.2-runtime (com.facebook.fbjni:fbjni:0.2.2) and jetified-fbjni-java-only-0.2 (com.facebook.fbjni:fbjni-java-only:0.2.2)
     Duplicate class com.facebook.jni.DestructorThread$DestructorList found in modules jetified-fbjni-0.2.2-runtime (com.facebook.fbjni:fbjni:0.2.2) and jetified-fbjni-java-only-0.2 (com.facebook.fbjni:fbjni-java-only:0.2.2)
     Duplicate class com.facebook.jni.DestructorThread$DestructorStack found in modules jetified-fbjni-0.2.2-runtime (com.facebook.fbjni:fbjni:0.2.2) and jetified-fbjni-java-only-0.2 (com.facebook.fbjni:fbjni-java-only:0.2.2)
     Duplicate class com.facebook.jni.DestructorThread$Terminus found in modules jetified-fbjni-0.2.2-runtime (com.facebook.fbjni:fbjni:0.2.2) and jetified-fbjni-java-only-0.2 (com.facebook.fbjni:fbjni-java-only:0.2.2)
     Duplicate class com.facebook.jni.HybridClassBase found in modules jetified-fbjni-0.2.2-runtime (com.facebook.fbjni:fbjni:0.2.2) and jetified-fbjni-java-only-0.2 (com.facebook.fbjni:fbjni-java-only:0.2.2)
     Duplicate class com.facebook.jni.HybridData found in modules jetified-fbjni-0.2.2-runtime (com.facebook.fbjni:fbjni:0.2.2) and jetified-fbjni-java-only-0.2 (com.facebook.fbjni:fbjni-java-only:0.2.2)
     Duplicate class com.facebook.jni.HybridData$Destructor found in modules jetified-fbjni-0.2.2-runtime (com.facebook.fbjni:fbjni:0.2.2) and jetified-fbjni-java-only-0.2 (com.facebook.fbjni:fbjni-java-only:0.2.2)
     Duplicate class com.facebook.jni.IteratorHelper found in modules jetified-fbjni-0.2.2-runtime (com.facebook.fbjni:fbjni:0.2.2) and jetified-fbjni-java-only-0.2 (com.facebook.fbjni:fbjni-java-only:0.2.2)
     Duplicate class com.facebook.jni.MapIteratorHelper found in modules jetified-fbjni-0.2.2-runtime (com.facebook.fbjni:fbjni:0.2.2) and jetified-fbjni-java-only-0.2 (com.facebook.fbjni:fbjni-java-only:0.2.2)
     Duplicate class com.facebook.jni.NativeRunnable found in modules jetified-fbjni-0.2.2-runtime (com.facebook.fbjni:fbjni:0.2.2) and jetified-fbjni-java-only-0.2 (com.facebook.fbjni:fbjni-java-only:0.2.2)
     Duplicate class com.facebook.jni.ThreadScopeSupport found in modules jetified-fbjni-0.2.2-runtime (com.facebook.fbjni:fbjni:0.2.2) and jetified-fbjni-java-only-0.2 (com.facebook.fbjni:fbjni-java-only:0.2.2)
     Duplicate class com.facebook.jni.UnknownCppException found in modules jetified-fbjni-0.2.2-runtime (com.facebook.fbjni:fbjni:0.2.2) and jetified-fbjni-java-only-0.2 (com.facebook.fbjni:fbjni-java-only:0.2.2)
     Duplicate class com.facebook.jni.annotations.DoNotStrip found in modules jetified-fbjni-0.2.2-runtime (com.facebook.fbjni:fbjni:0.2.2) and jetified-fbjni-java-only-0.2 (com.facebook.fbjni:fbjni-java-only:0.2.2)
     
     Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
Note: /home/somvt/onepoint/templates/OnePoint/node_modules/@react-native-async-storage/async-storage/android/src/main/java/com/reactnativecommunity/asyncstorage/AsyncStorageModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/somvt/onepoint/templates/OnePoint/node_modules/@react-native-async-storage/async-storage/android/src/main/java/com/reactnativecommunity/asyncstorage/AsyncStoragePackage.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class com.facebook.jni.CppException found in modules jetified-fbjni-0.2.2-runtime (com.facebook.fbjni:fbjni:0.2.2) and jetified-fbjni-java-only-0.2 (com.facebook.fbjni:fbjni-java-only:0.2.2)
     Duplicate class com.facebook.jni.CppSystemErrorException found in modules jetified-fbjni-0.2.2-runtime (com.facebook.fbjni:fbjni:0.2.2) and jetified-fbjni-java-only-0.2 (com.facebook.fbjni:fbjni-java-only:0.2.2)
     Duplicate class com.facebook.jni.DestructorThread found in modules jetified-fbjni-0.2.2-runtime (com.facebook.fbjni:fbjni:0.2.2) and jetified-fbjni-java-only-0.2 (com.facebook.fbjni:fbjni-java-only:0.2.2)
     Duplicate class com.facebook.jni.DestructorThread$1 found in modules jetified-fbjni-0.2.2-runtime (com.facebook.fbjni:fbjni:0.2.2) and jetified-fbjni-java-only-0.2 (com.facebook.fbjni:fbjni-java-only:0.2.2)
     Duplicate class com.facebook.jni.DestructorThread$Destructor found in modules jetified-fbjni-0.2.2-runtime (com.facebook.fbjni:fbjni:0.2.2) and jetified-fbjni-java-only-0.2 (com.facebook.fbjni:fbjni-java-only:0.2.2)
     Duplicate class com.facebook.jni.DestructorThread$DestructorList found in modules jetified-fbjni-0.2.2-runtime (com.facebook.fbjni:fbjni:0.2.2) and jetified-fbjni-java-only-0.2 (com.facebook.fbjni:fbjni-java-only:0.2.2)
     Duplicate class com.facebook.jni.DestructorThread$DestructorStack found in modules jetified-fbjni-0.2.2-runtime (com.facebook.fbjni:fbjni:0.2.2) and jetified-fbjni-java-only-0.2 (com.facebook.fbjni:fbjni-java-only:0.2.2)
     Duplicate class com.facebook.jni.DestructorThread$Terminus found in modules jetified-fbjni-0.2.2-runtime (com.facebook.fbjni:fbjni:0.2.2) and jetified-fbjni-java-only-0.2 (com.facebook.fbjni:fbjni-java-only:0.2.2)
     Duplicate class com.facebook.jni.HybridClassBase found in modules jetified-fbjni-0.2.2-runtime (com.facebook.fbjni:fbjni:0.2.2) and jetified-fbjni-java-only-0.2 (com.facebook.fbjni:fbjni-java-only:0.2.2)
     Duplicate class com.facebook.jni.HybridData found in modules jetified-fbjni-0.2.2-runtime (com.facebook.fbjni:fbjni:0.2.2) and jetified-fbjni-java-only-0.2 (com.facebook.fbjni:fbjni-java-only:0.2.2)
     Duplicate class com.facebook.jni.HybridData$Destructor found in modules jetified-fbjni-0.2.2-runtime (com.facebook.fbjni:fbjni:0.2.2) and jetified-fbjni-java-only-0.2 (com.facebook.fbjni:fbjni-java-only:0.2.2)
     Duplicate class com.facebook.jni.IteratorHelper found in modules jetified-fbjni-0.2.2-runtime (com.facebook.fbjni:fbjni:0.2.2) and jetified-fbjni-java-only-0.2 (com.facebook.fbjni:fbjni-java-only:0.2.2)
     Duplicate class com.facebook.jni.MapIteratorHelper found in modules jetified-fbjni-0.2.2-runtime (com.facebook.fbjni:fbjni:0.2.2) and jetified-fbjni-java-only-0.2 (com.facebook.fbjni:fbjni-java-only:0.2.2)
     Duplicate class com.facebook.jni.NativeRunnable found in modules jetified-fbjni-0.2.2-runtime (com.facebook.fbjni:fbjni:0.2.2) and jetified-fbjni-java-only-0.2 (com.facebook.fbjni:fbjni-java-only:0.2.2)
     Duplicate class com.facebook.jni.ThreadScopeSupport found in modules jetified-fbjni-0.2.2-runtime (com.facebook.fbjni:fbjni:0.2.2) and jetified-fbjni-java-only-0.2 (com.facebook.fbjni:fbjni-java-only:0.2.2)
     Duplicate class com.facebook.jni.UnknownCppException found in modules jetified-fbjni-0.2.2-runtime (com.facebook.fbjni:fbjni:0.2.2) and jetified-fbjni-java-only-0.2 (com.facebook.fbjni:fbjni-java-only:0.2.2)
     Duplicate class com.facebook.jni.annotations.DoNotStrip found in modules jetified-fbjni-0.2.2-runtime (com.facebook.fbjni:fbjni:0.2.2) and jetified-fbjni-java-only-0.2 (com.facebook.fbjni:fbjni-java-only:0.2.2)
     
     Go to the documentation to learn how to <a href="d.android.com/r/tools/classpath-sync-errors">Fix dependency resolution errors</a>.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s

    at makeError (/home/somvt/onepoint/templates/OnePoint/node_modules/@react-native-community/cli-platform-android/node_modules/execa/index.js:174:9)
    at /home/somvt/onepoint/templates/OnePoint/node_modules/@react-native-community/cli-platform-android/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/home/somvt/onepoint/templates/OnePoint/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:109:5)
    at async Command.handleAction (/home/somvt/onepoint/templates/OnePoint/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js:192:9)
info Run CLI with --verbose flag for more details.
```
Currently, I have absolutely no clue as to why is this happening. I haven't seen other users complaining about this issue, so I think it's probably something to do with my node installation and packages. I tried googling and searching on stack-overflow, but it was clearly some dependency error for which solutions were fine-tuned to particular libraries. 

Could I get some help as to how should I resolve this issue? I am not used to debugging react-native problems as I am a beginner, and I would love if someone could point out where could I make changes.

**Comment by JeremyDolle** [comment]
Ok @SomTambe we will check together,

First be sure to have all the required environment for using react-native

Next did you have a similar issue with iOS ?

After running the `npm install` command all was successful ? A fullyfilled node_modules, a package_lock file ?
