### ISSUE TITLE
Writing Unit Tests on Theme using Jest

### ISSUE THREAD

**Issue by erayaras** [thecodingmachine/react-native-boilerplate#253]
Hello,

I want to test my components.

Here is my component;

```
import React from 'react'
import { View, TouchableOpacity, Text } from 'react-native'
import { useTheme } from '@/Theme'

const Button = ({onPress, text}) => {
  const { Layout, Common, Fonts } = useTheme()

  return (
    <View style={[[Layout.center], { flex: 1 }]}>
      <TouchableOpacity
        style={[[Common.button.solidRounded]]}
        onPress={onPress}
      >
        <Text style={[[Fonts.textInterSemiBold16]]}>
          {text}
        </Text>
      </TouchableOpacity>
    </View>
  )
}

export default Button
```

Here is my test;

```
import React from 'react'
import { render } from '@testing-library/react-native';
import Button from '../src/Components/Button';
import { Provider } from 'react-redux'
import configureStore from 'redux-mock-store'

describe('With React Testing Library', () => {
  const initialState = {output:10}
  const mockStore = configureStore()
  let store,wrapper

  it('Renders Button correctly"', () => {
    store = mockStore(initialState)
    const { getByText } = render(<Provider store={store}><Button /></Provider>)
  })
})
```

Here is the error I get;

```
With React Testing Library
    ✕ Renders Button correctly" (35 ms)

  ● With React Testing Library › Renders Button correctly"

    TypeError: Cannot read properties of undefined (reading 'theme')

      15 |
      16 |   // Get current theme from the store
    > 17 |   const currentTheme = useSelector(state => state.theme.theme || 'default')
         |                                                         ^
      18 |   const isDark = useSelector(state => state.theme.darkMode)
      19 |   const darkMode = isDark === null ? colorScheme === 'light' : isDark
      20 |   // const darkMode = isDark === null ? colorScheme === 'dark' : isDark /////////////

      at src/Theme/hooks/useTheme.js:17:57
      at useSelectorWithStoreAndSubscription (node_modules/react-redux/lib/hooks/useSelector.js:41:30)
      at useSelector (node_modules/react-redux/lib/hooks/useSelector.js:137:25)
      at _default (src/Theme/hooks/useTheme.js:17:24)
      at Button (src/Components/Button.js:6:37)
      at renderWithHooks (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6016:18)
      at mountIndeterminateComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8744:13)
      at beginWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9966:16)
      at performUnitOfWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13800:12)
      at workLoopSync (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13728:5)
      at renderRootSync (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13691:7)
      at performSyncWorkOnRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13404:18)
      at node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2537:26
      at unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:468:12)
      at runWithPriority (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2486:10)
      at flushSyncCallbackQueueImpl (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2532:9)
      at flushSyncCallbackQueue (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2519:3)
      at batchedUpdates (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13459:7)
      at act (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15280:14)
      at renderWithAct (node_modules/@testing-library/react-native/build/render.js:75:20)
      at render (node_modules/@testing-library/react-native/build/render.js:46:20)
      at Object.<anonymous> (__tests__/button.test.js:51:27)

  console.error
    The above error occurred in the <Button> component:

        at Button (/Users/appApp/Desktop/app/appApp/src/Components/Button.js:5:18)
        at Provider (/Users/appApp/Desktop/app/appApp/node_modules/react-redux/lib/components/Provider.js:21:20)

    Consider adding an error boundary to your tree to customize error handling behavior.
    Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.

      at logCapturedError (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10989:23)
      at update.callback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11022:5)
      at callCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:3662:12)
      at commitUpdateQueue (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:3683:9)
      at commitLifeCycles (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11855:11)
      at commitLayoutEffects (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:14443:7)
      at HTMLUnknownElement.callCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11391:14)
```

So If I use `const { Layout, Common, Fonts } = useTheme()` in my component, the test is failed. 
How can I test my component along with Theme using Jest?

**Comment by JeremyDolle** [comment]
Hi @erayaras The theme use the store in order to keep the preferences of the user. I saw that you mock the store with an initial state. That's good but it missing some parameters. The boilerplate comes with this default state : 
```
{ theme: null, darkMode: null }
```

So I think this is missing and that's why the error said that `Cannot read properties of undefined (reading 'theme')`

Tell me if it's ok and close the issue

**Comment by erayaras** [comment]
Thanks for reply @JeremyDolle.

I changed the `initialState` as `const initialState = { theme: null, darkMode: 'dark' }` and `const initialState = { theme: null, darkMode: null }`.

Still I got the same error.

I think somehow I need to pass theme to test like provider but I don't know how to do that.

Do you have any other idea?

**Comment by JeremyDolle** [comment]
Yes sorry my bad their is a `theme` slice so you need to have:

```
const initialState = {
   theme: {
      theme: null,
      dark: null
   }
}
```

**Comment by erayaras** [comment]
Thank you, this is worked.

**Comment by erayaras** [comment]
Hi @JeremyDolle, I have similar issue on Login screen and I spent yesterday but couldn't figure out what should be the `initialState` for my login screen. If you could help, I would be very happy.

Here is my Login Store;

```
import {
  buildAsyncState,
  buildAsyncReducers,
  buildAsyncActions,
} from '@thecodingmachine/redux-toolkit-wrapper'
import fetchLoginService from '@/Services/Login/FetchLogin'

export default {
  initialState: {fetchLogin:{item:null, loading: false, error:null}},
  action: buildAsyncActions('login/fetchLogin', fetchLoginService),
  reducers: buildAsyncReducers({
    itemKey: 'fetchLogin.item', // Optionally, if you scoped variables, you can use a key with dot notation
    errorKey: 'fetchLogin.error', // Optionally, if you scoped variables, you can use a key with dot notation
    loadingKey: 'fetchLogin.loading',
  }),
}
```

```
import { buildSlice } from '@thecodingmachine/redux-toolkit-wrapper'
import FetchLogin from './FetchLogin'

// This state is common to all the "login" module, and can be modified by any "login" reducers
const sliceInitialState = {}
// const sliceInitialState = {
//   item: {},
// }

export default buildSlice('login', [FetchLogin], sliceInitialState).reducer
```
My `initialState`;

```
  const initialState = {
    login: {
      fetchLogin: {
        item: null,
        loading: false,
        error: null
      }
    }
  }
```

Error I get;

```
 TypeError: Cannot read properties of undefined (reading 'initialState')

       8 | // }
       9 |
    > 10 | export default buildSlice('login', [FetchLogin], sliceInitialState).reducer
         |                ^
      11 | // export default buildSlice('login', [FetchLogin], sliceInitialState).reducer
      12 |

      at node_modules/@thecodingmachine/redux-toolkit-wrapper/lib/wrappers/slice/buildSlice.js:32:57
          at Array.reduce (<anonymous>)
      at buildSlice (node_modules/@thecodingmachine/redux-toolkit-wrapper/lib/wrappers/slice/buildSlice.js:31:30)
      at Object.<anonymous> (src/Store/Login/index.js:10:16)
      at Object.<anonymous> (src/Store/index.js:16:1)
      at Object.<anonymous> (src/Services/index.js:8:1)
      at Object.<anonymous> (src/Services/Login/FetchLogin.js:2:1)
      at Object.<anonymous> (src/Store/Login/FetchLogin.js:22:1)
      at Object.<anonymous> (src/Components/CustomDrawer.js:6:1)
      at Object.<anonymous> (src/Components/index.js:26:1)
      at Object.<anonymous> (src/Containers/Login/Index.js:16:1)
      at Object.<anonymous> (__tests__/login.test.js:7:1)

```

**Comment by JeremyDolle** [comment]
Can you share your test please

**Comment by erayaras** [comment]
Here is my test;

```
import React from 'react';
import { render, fireEvent, waitFor } from '@testing-library/react-native';
import { NavigationContainer } from '@react-navigation/native';
import { Provider } from 'react-redux'
import configureStore from 'redux-mock-store'
import { Login } from '@/Containers/Login';

describe('Screen 1', () => {
  const initialState = {
    Login: {
      fetchLogin: {
        item: null,
        loading: false,
        error: null
      }
    }
  }
  const mockStore = configureStore()
  let store, wrapper
  store = mockStore(initialState)

  it('navigates on button press', () => {
    const push = jest.fn();
    const { getByText } = render(<Provider store={store}><Login navigation={{ push }} /></Provider>);
    fireEvent.press(getByText('Login'));
    expect(push).toHaveBeenCalledWith('Screen2');
  });
});
```

I found that importing container cause this error. Because if I comment the rest of the code except importing the container I still get the same error. For example if I only have this line `import { Login } from '@/Containers/Login'` in my test code, I get same error.

Also, I found that regardless of the imported container, I get the same error except for two of my containers.
For example If I import `import { Search } from '@/Containers/Search'` I still get ;

```
TypeError: Cannot read properties of undefined (reading 'initialState')

       8 | // }
       9 |
    > 10 | export default buildSlice('login', [FetchLogin], sliceInitialState).reducer
         |                ^
      11 |

      at node_modules/@thecodingmachine/redux-toolkit-wrapper/lib/wrappers/slice/buildSlice.js:32:57
          at Array.reduce (<anonymous>)
      at buildSlice (node_modules/@thecodingmachine/redux-toolkit-wrapper/lib/wrappers/slice/buildSlice.js:31:30)
      at Object.<anonymous> (src/Store/Login/index.js:10:16)
      at Object.<anonymous> (src/Store/index.js:16:1)
      at Object.<anonymous> (src/Services/index.js:8:1)
      at Object.<anonymous> (src/Services/Login/FetchLogin.js:2:1)
      at Object.<anonymous> (src/Store/Login/FetchLogin.js:22:1)
      at Object.<anonymous> (src/Components/CustomDrawer.js:6:1)
      at Object.<anonymous> (src/Components/index.js:26:1)
      at Object.<anonymous> (src/Containers/Search/Index.js:21:1)
      at Object.<anonymous> (__tests__/search.test.js:7:1)
```

This does not apply only to a couple of my containers but I couldn't understand the underlying cause of this.

**Comment by JeremyDolle** [comment]
Could you please share a reproductable repository it could be easier for me to test and see the entier code ?

**Comment by erayaras** [comment]
Thanks, I will do it on the weekend.
