### ISSUE TITLE
[BUG]: error while installing depedencies

### ISSUE THREAD

**Issue by sseppo** [thecodingmachine/react-native-boilerplate#379]
### react-native environment setup

- [X] I verified that I have not react-native-cli installed globally and be up to date about the React Native environment setup.

### Description

I was running the basic installation of the template:
`npx react-native@latest init MyApp --template @thecodingmachine/react-native-boilerplate`

While at it, I got following errors when process was at point "Installing depedencies"

Node is of version 18.17.1 (happened also at Node 18.12.1 which I tried first). I chose the Typescript version, but after the error tired also with Javascript which also had erros, just different ones.  

```
× Installing dependencies
error Command failed with exit code 2147483651: npm install


#
# Fatal error in , line 0
# Check failed: addr + size <= chunk_->area_end().
#
#
#
#FailureMessage Object: 0000008F087FF1D0
 1: 00007FF75BFD07BF node_api_throw_syntax_error+175823
 2: 00007FF75BEE630F v8::CTypeInfoBuilder<void>::Build+12559
 3: 00007FF75CDA3732 V8_Fatal+162
 4: 00007FF75C7FF98F v8::internal::GCTracer::AddScopeSample+751
 5: 00007FF75C8016FD v8::internal::MarkingWorklists::Local::PushWrapper+1613
 6: 00007FF75C80089F v8::internal::InvalidatedSlotsFilter::NextInvalidatedObject+239
 7: 00007FF75C8021D2 v8::internal::MarkingWorklists::Local::PushWrapper+4386
 8: 00007FF75C802057 v8::internal::MarkingWorklists::Local::PushWrapper+4007
 9: 00007FF75CB729D0 v8::internal::SetupIsolateDelegate::SetupHeap+1437648
10: 00007FF75BEE8CED v8::internal::interpreter::BytecodeArrayWriter::constant_array_builder+813
11: 00007FF75C01C88D uv_poll_stop+237
12: 00007FF75D0348A0 inflateValidate+151888
13: 00007FFDC4B67614 BaseThreadInitThunk+20
14: 00007FFDC5CA26A1 RtlUserThreadStart+33.
Error: Command failed with exit code 2147483651: npm install


#
# Fatal error in , line 0
# Check failed: addr + size <= chunk_->area_end().
#
#
#
#FailureMessage Object: 0000008F087FF1D0
 1: 00007FF75BFD07BF node_api_throw_syntax_error+175823
 2: 00007FF75BEE630F v8::CTypeInfoBuilder<void>::Build+12559
 3: 00007FF75CDA3732 V8_Fatal+162
 4: 00007FF75C7FF98F v8::internal::GCTracer::AddScopeSample+751
 5: 00007FF75C8016FD v8::internal::MarkingWorklists::Local::PushWrapper+1613
 6: 00007FF75C80089F v8::internal::InvalidatedSlotsFilter::NextInvalidatedObject+239
 7: 00007FF75C8021D2 v8::internal::MarkingWorklists::Local::PushWrapper+4386
 8: 00007FF75C802057 v8::internal::MarkingWorklists::Local::PushWrapper+4007
 9: 00007FF75CB729D0 v8::internal::SetupIsolateDelegate::SetupHeap+1437648
10: 00007FF75BEE8CED v8::internal::interpreter::BytecodeArrayWriter::constant_array_builder+813
11: 00007FF75C01C88D uv_poll_stop+237
12: 00007FF75D0348A0 inflateValidate+151888
13: 00007FFDC4B67614 BaseThreadInitThunk+20
14: 00007FFDC5CA26A1 RtlUserThreadStart+33
    at makeError (C:\Users\Mike\AppData\Local\npm-cache\_npx\dea611a43221eddd\node_modules\execa\lib\error.js:60:11)
    at handlePromise (C:\Users\Mike\AppData\Local\npm-cache\_npx\dea611a43221eddd\node_modules\execa\index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async installDependencies (C:\Users\Mike\AppData\Local\npm-cache\_npx\dea611a43221eddd\node_modules\@react-native-community\cli\build\commands\init\init.js:143:3)
    at async createFromTemplate (C:\Users\Mike\AppData\Local\npm-cache\_npx\dea611a43221eddd\node_modules\@react-native-community\cli\build\commands\init\init.js:120:7)
    at async Object.initialize [as func] (C:\Users\Mike\AppData\Local\npm-cache\_npx\dea611a43221eddd\node_modules\@react-native-community\cli\build\commands\init\init.js:184:3)
    at async Command.handleAction (C:\Users\Mike\AppData\Local\npm-cache\_npx\dea611a43221eddd\node_modules\@react-native-community\cli\build\index.js:109:9)
```

### Version

3.7.2

### Do you use TypeScript?

- [X] Yes
- [ ] No

### On which OS this issue appear on?

- [ ] IOS
- [ ] Android

### Desktop OS

Windows 10

**Comment by sseppo** [comment]
Got it installed, with using --npm -option at the end of the npx - command. So I guess that related to yarn failing

**Comment by JeremyDolle** [comment]
Hello the error seams to be related to the cli not the boilerplate. 
Did you try without the npm option ?
