### ISSUE TITLE
[BUG]: Failed run project

### ISSUE THREAD

**Issue by davidas13** [thecodingmachine/react-native-boilerplate#400]
### react-native environment setup

- [X] I verified that I have not react-native-cli installed globally and be up to date about the React Native environment setup.

### Description

I got error message `config Validation Error: "project.ios.automaticPodsInstallation" is not allowed` when running project.

```
error Failed to load configuration of your project.
Config Validation Error: "project.ios.automaticPodsInstallation" is not allowed
    at readConfigFromDisk (../MyApp/node_modules/@react-native-community/cli-config/build/readConfigFromDisk.js:52:11)
    at loadConfig (../MyApp/node_modules/@react-native-community/cli-config/build/loadConfig.js:65:65)
    at setupAndRun (../MyApp/node_modules/@react-native-community/cli/build/index.js:159:39)
    at Object.run (../MyApp/node_modules/@react-native-community/cli/build/index.js:129:11)
    at Object.<anonymous> (../MyApp/node_modules/react-native/cli.js:16:7)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
error Command failed with exit code 1.
```

### Version

4.0.0

### Do you use TypeScript?

- [ ] Yes
- [X] No

### On which OS this issue appear on?

- [X] IOS
- [ ] Android

### Desktop OS

Macos

**Comment by JeremyDolle** [comment]
When did you get this error? Give me the steps to reproduce please.

**Comment by yinpinglai** [comment]
I got the same issue when I was trying to create a new project. What I did as below:
1. npx react-native@latest init MyApp --template @thecodingmachine/react-native-boilerplate
2. Answer `y` for typescript.
3. Answer `n` for installing Cocoapods now.
4. `cd "../MyApp" && npx react-native run-ios`

**Comment by Pakile** [comment]
I encountered the same issue. After commenting on the line automaticPodsInstallation: true in the react-native.config.js file, it started working.

**Comment by yinpinglai** [comment]
Thank you. I could run the project now. I removed the line `automaticPodsInstallation: true` in the `react-native.config.js` file and then I manually install all pod dependencies. It worked.
