### ISSUE TITLE
[BUG]: Error when create new project

### ISSUE THREAD

**Issue by phungxuanvuong97** [thecodingmachine/react-native-boilerplate#402]
### react-native environment setup

- [X] I verified that I have not react-native-cli installed globally and be up to date about the React Native environment setup.

### Description

I already installed dependencies by following official document.

Then  I run this command:
npx react-native@latest init MyApp --template @thecodingmachine/react-native-boilerplate
I get this error:
`Do you want to install CocoaPods now? Only needed if you run your project in Xcode directly … yes
✔ Installing Ruby Gems
✖ Installing CocoaPods dependencies  (this may take a few minutes)
error Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
NOTE: Gem::Platform.match is deprecated; use Gem::Platform.match_spec? or match_gem? instead. It will be removed in Rubygems 4
Gem::Platform.match called from /Users/phungvuong/Documents/coding/Application/HomeRentail/vendor/bundle/ruby/3.2.0/gems/bundler-2.1.4/lib/bundler/index.rb:198.
error Failed to load configuration of your project.
✖ Installing CocoaPods dependencies  (this may take a few minutes)
error Looks like your iOS environment is not properly set. Please go to https://reactnative.dev/docs/environment-setup?os=macos&platform=ios&guide=native and follow the React Native CLI QuickStart guide for macOS and iOS.
info Run CLI with --verbose flag for more details.
phungvuong@phungs-MacBook-Pro Application %`

Then I tried to run app but no lucky.

`phungvuong@phungs-MacBook-Pro HomeRentail % yarn ios 
yarn run v1.22.19
$ react-native run-ios
error Failed to load configuration of your project.
Config Validation Error: "project.ios.automaticPodsInstallation" is not allowed
    at readConfigFromDisk (/Users/phungvuong/Documents/coding/Application/HomeRentail/node_modules/@react-native-community/cli-config/build/readConfigFromDisk.js:52:11)
    at loadConfig (/Users/phungvuong/Documents/coding/Application/HomeRentail/node_modules/@react-native-community/cli-config/build/loadConfig.js:65:65)
    at setupAndRun (/Users/phungvuong/Documents/coding/Application/HomeRentail/node_modules/@react-native-community/cli/build/index.js:159:39)
    at run (/Users/phungvuong/Documents/coding/Application/HomeRentail/node_modules/@react-native-community/cli/build/index.js:129:11)
    at Object.<anonymous> (/Users/phungvuong/Documents/coding/Application/HomeRentail/node_modules/@react-native-community/cli/build/bin.js:31:3)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
phungvuong@phungs-MacBook-Pro HomeRentail % `

### Version

4.0

### Do you use TypeScript?

- [X] Yes
- [ ] No

### On which OS this issue appear on?

- [X] IOS
- [ ] Android

### Desktop OS

Macbook pro 2020

**Comment by didoshotev** [comment]
Same issue here

**Comment by imAunAbbas** [comment]
I'm encountering the same pod installation issue when creating a new project with boilerplate version 4. While the project runs smoothly on Android, it fails on iOS. This specific error occurs during initial pod installation as part of the project creation process, and remains unresolved regardless of further attempts to install pods manually.

**Comment by JeremyDolle** [comment]
Can you retry with the new version. Cannot reproduce on my side

**Comment by JeremyDolle** [comment]
Close due to inactivity. Feel free to re-open if needed
