### ISSUE TITLE
Jest test: ReferenceError: You are trying to `import` a file after the Jest environment has been torn down.

### ISSUE THREAD

**Issue by mboettcher** [thecodingmachine/react-native-boilerplate#50]
Hi -

I set up the boilerplate and the app works in the simulator. However, the jest test keeps failing. 

`ReferenceError: You are trying to import a file after the Jest environment has been torn down.

      at Object.get BackHandler [as BackHandler] (node_modules/react-native/Libraries/react-native/react-native-implementation.js:222:12)
      at new NavigationContainer (node_modules/@react-navigation/native/dist/createAppContainer.js:204:47)
      at constructClassInstance (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:3435:18)
      at updateClassComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6606:5)
      at beginWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7563:16)

ReferenceError: You are trying to import a file after the Jest environment has been torn down.

      at Object.get getNavigation [as getNavigation] (node_modules/@react-navigation/core/lib/commonjs/index.js:7:12)
      at NavigationContainer.render (node_modules/@react-navigation/native/dist/createAppContainer.js:464:42)
      at finishClassComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6660:31)
      at updateClassComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6615:24)
      at beginWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7563:16)
 PASS  __tests__/App-test.js
  ✓ renders correctly (9ms)

  console.error node_modules/fbjs/lib/warning.js:30
    Warning: Async Storage has been extracted from react-native core and will be removed in a future release. It can now be installed and imported from '@react-native-community/async-storage' instead of 'react-native'. See https://github.com/react-native-community/react-native-async-storage

  console.error node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9036
    The above error occurred in the <NavigationContainer> component:
        in NavigationContainer (created by RootScreen)
        in View (created by View)
        in View (created by RootScreen)
        in RootScreen (created by ConnectFunction)
        in ConnectFunction (created by App)
        in PersistGate (created by App)
        in Provider (created by App)
        in App
    
    Consider adding an error boundary to your tree to customize error handling behavior.
    Visit https://fb.me/react-error-boundaries to learn more about error boundaries.

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        3.207s
Ran all test suites.
Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
npm ERR! Test failed.  See above for more details.`

npx envinfo --preset jest

  Binaries:
    Node: 12.4.0 - /usr/local/bin/node
    Yarn: 1.17.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  npmPackages:
    jest: ^24.8.0 => 24.8.0 

Thanks and best regards
Martin

**Comment by AurelGit** [comment]
Hey @mboettcher !

Thanks for your precious feedback.

I've just merged #51. It should resolve your issue.

Let's keep in touch :)

**Comment by mboettcher** [comment]
thanks, works now :)

**Comment by shubhamkakkar** [comment]
still facing the same issue
