### ISSUE TITLE
Broken Boilerplate?

### ISSUE THREAD

**Issue by OriginalTsynn** [thecodingmachine/react-native-boilerplate#59]
error: bundling failed: Error: While resolving module `App/Config`, the Haste package `App` was found. However the module `Config` could not be found within the package. Indeed, none of these files exist:

  * `/Users/slevin/SEI/ReactNative/react-native-boilerplate/App/Config(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)`
  * `/Users/slevin/SEI/ReactNative/react-native-boilerplate/App/Config/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)`
    at resolveHasteName (/Users/slevin/SEI/ReactNative/react-native-boilerplate/node_modules/metro-resolver/src/resolve.js:236:9)
    at Object.resolve (/Users/slevin/SEI/ReactNative/react-native-boilerplate/node_modules/metro-resolver/src/resolve.js:103:20)
    at ModuleResolver.resolveDependency (/Users/slevin/SEI/ReactNative/react-native-boilerplate/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:143:31)
    at ResolutionRequest.resolveDependency (/Users/slevin/SEI/ReactNative/react-native-boilerplate/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/Users/slevin/SEI/ReactNative/react-native-boilerplate/node_modules/metro/src/node-haste/DependencyGraph.js:283:16)
    at Object.resolve (/Users/slevin/SEI/ReactNative/react-native-boilerplate/node_modules/metro/src/lib/transformHelpers.js:261:42)
    at /Users/slevin/SEI/ReactNative/react-native-boilerplate/node_modules/metro/src/DeltaBundler/traverseDependencies.js:399:31
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/slevin/SEI/ReactNative/react-native-boilerplate/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:18)
    at /Users/slevin/SEI/ReactNative/react-native-boilerplate/node_modules/metro/src/DeltaBundler/traverseDependencies.js:269:33
 BUNDLE  [ios, dev] ./index.js ▓▓▓▓▓▓▓▓▓░░░░░░░ 62.2% (583/739), failed.

**Describe the bug**
Not entirely sure what the problem is, it's simply failing to launch in the iOS simulator for me

**To Reproduce**
1. clone the repository git clone https://github.com/thecodingmachine/react-native-boilerplate
2. remove the previous git history: rm -rf .git/
3. install the npm dependencies by running yarn
4. in the project root folder: react-native run-ios

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/48529599/61006546-95e7c000-a338-11e9-9104-7e4e8e714c53.png)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by OriginalTsynn** [comment]
resolved the issue!

**Comment by AurelGit** [comment]
Missing the `App/Config/index.js` file I guess ;)

See you !

**Comment by braynm** [comment]
@OriginalTsynn Hi, I am having the same error. would you mind sharing how did it get fixed? Thanks!

**Comment by shahidmau** [comment]
I was facing the same issue and fixed by renaming App/Config/index.dev.js to App/Config/index.js
