### ISSUE TITLE
Get Error while running react-native run-android

### ISSUE THREAD

**Issue by merajcal** [thecodingmachine/react-native-boilerplate#79]
Looking for JS files in
   /Users/momeraj/Documents/cisco/tutorials/react-native/react-native-boilerplate

warning: the transform cache was reset.
Loading dependency graph, done.
error: bundling failed: Error: While resolving module `App/Config`, the Haste package `App` was found. However the module `Config` could not be found within the package. Indeed, none of these files exist:

  * `/Users/momeraj/Documents/cisco/tutorials/react-native/react-native-boilerplate/App/Config(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
  * `/Users/momeraj/Documents/cisco/tutorials/react-native/react-native-boilerplate/App/Config/index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
    at resolveHasteName (/Users/momeraj/Documents/cisco/tutorials/react-native/react-native-boilerplate/node_modules/metro-resolver/src/resolve.js:236:9)
    at Object.resolve (/Users/momeraj/Documents/cisco/tutorials/react-native/react-native-boilerplate/node_modules/metro-resolver/src/resolve.js:103:20)
    at ModuleResolver.resolveDependency (/Users/momeraj/Documents/cisco/tutorials/react-native/react-native-boilerplate/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:143:31)
    at ResolutionRequest.resolveDependency (/Users/momeraj/Documents/cisco/tutorials/react-native/react-native-boilerplate/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/Users/momeraj/Documents/cisco/tutorials/react-native/react-native-boilerplate/node_modules/metro/src/node-haste/DependencyGraph.js:283:16)
    at Object.resolve (/Users/momeraj/Documents/cisco/tutorials/react-native/react-native-boilerplate/node_modules/metro/src/lib/transformHelpers.js:264:42)
    at dependencies.map.result (/Users/momeraj/Documents/cisco/tutorials/react-native/react-native-boilerplate/node_modules/metro/src/DeltaBundler/traverseDependencies.js:399:31)
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/momeraj/Documents/cisco/tutorials/react-native/react-native-boilerplate/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:18)
    at /Users/momeraj/Documents/cisco/tutorials/react-native/react-native-boilerplate/node_modules/metro/src/DeltaBundler/traverseDependencies.js:269:33
 BUNDLE  [android, dev] ./index.js ▓▓▓▓▓▓▓░░░░░░░░░ 49.0% (300/511)::ffff:127.0.0.1 - - [25/Sep/2019:09:32:23 +0000] "GET /index.bundle?platform=android&dev=true&minify=false HTTP/1.1" 500 - "-" "okhttp/3.12.1"
 BUNDLE  [android, dev] ./index.js ▓▓▓▓▓▓▓░░░░░░░░░ 49.0% (300/511), failed.

**Comment by AurelGit** [comment]
Hello @merajcal .

Please create a index.js file as specified in the documentation.

https://github.com/thecodingmachine/react-native-boilerplate#running-the-project

**Comment by merajcal** [comment]
Sorry, My bad. Just realized. Thanks

**Comment by arvind-bookbox** [comment]
> 
> 
> Hello @merajcal .
> 
> Please create a index.js file as specified in the documentation.
> 
> https://github.com/thecodingmachine/react-native-boilerplate#running-the-project

Hi @AurelGit 
I'm having this same issue. I visited the link and couldn't find info on creating a 'index.js' file!
How do I create this file or there is another link to help with this?
Do let me know if I missed any info since I'm new to  react-native app development.
Thanks

**Comment by JeremyDolle** [comment]
Hi @arvind-bookbox, welcome on the react-native community :wink:
This issue dates from the version 1 ! Now we are on version 2 🚀.
Let me know what error is display in your metro bundler ? Is it the exact same : `error: bundling failed: Error: While resolving module App/Config, the Haste package App was found. However the module Config could not be found within the package. Indeed, none of these files exist:` ?

**Comment by arvind-bookbox** [comment]
> 
> 
> Hi @arvind-bookbox, welcome on the react-native community 😉
> This issue dates from the version 1 ! Now we are on version 2 🚀.
> Let me know what error is display in your metro bundler ? Is it the exact same : `error: bundling failed: Error: While resolving module App/Config, the Haste package App was found. However the module Config could not be found within the package. Indeed, none of these files exist:` ?

Hello Jeremy :)
Yes it is the same error. any ideas on how to fix this?

**Comment by JeremyDolle** [comment]
Did you create you project with the command `npx react-native init MyApp --template @thecodingmachine/react-native-boilerplate`. Are you using the V2 of the boilerplate ? Because `App/Config` isn't present anymore in the boilerplate. Now it's `src/Config`. So having the same error as above is a little strange if you are using the V2

**Comment by arvind-bookbox** [comment]
Hi, 
I'm not using v2. 
In fact this issue is happening in a project that I had moved from a friend. since I get the same error, I posted here.

Once I was able to get this working by renaming index.dev.js to index.js in App/Config folder. But this time I do not have any index.dev.js only index.production.js and index.staging.js files.

Since I'm new to react-native I find it difficult to understand the reason on how things can work or not!
Please advise. Thanks.

**Comment by JeremyDolle** [comment]
Ok that's make sens ! 
I recommend using the V2 but there are a lot of breaking change. But if your are new in react-native the V2 will help you a lot.
By the way in App/Config you have to have a index.js file, this will be the file used for environment variables. So event if you have a index.dev.js you can copy paste index.staging.js into a index.js file. This will resolve your issue

**Comment by arvind-bookbox** [comment]
Hi Jeremy thanks for your support.
I did rename index.staging.js to index.js but still the issue persists.
Here is the full output from Metro window.

`error: bundling failed: Error: While resolving module `App/Config`, the Haste package `App` was found. However the module `Config` could not be found within the package. Indeed, none of these files exist:

  * `D:\PR-BBX_Projects\BookBoxApp\App\Config(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
  * `D:\PR-BBX_Projects\BookBoxApp\App\Config\index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
    at resolveHasteName (D:\PR-BBX_Projects\BookBoxApp\node_modules\metro-resolver\src\resolve.js:236:9)
    at Object.resolve (D:\PR-BBX_Projects\BookBoxApp\node_modules\metro-resolver\src\resolve.js:103:20)
    at ModuleResolver.resolveDependency (D:\PR-BBX_Projects\BookBoxApp\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:143:31)
    at ResolutionRequest.resolveDependency (D:\PR-BBX_Projects\BookBoxApp\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (D:\PR-BBX_Projects\BookBoxApp\node_modules\metro\src\node-haste\DependencyGraph.js:283:16)
    at Object.resolve (D:\PR-BBX_Projects\BookBoxApp\node_modules\metro\src\lib\transformHelpers.js:261:42)
    at D:\PR-BBX_Projects\BookBoxApp\node_modules\metro\src\DeltaBundler\traverseDependencies.js:399:31
    at Array.map (<anonymous>)
    at resolveDependencies (D:\PR-BBX_Projects\BookBoxApp\node_modules\metro\src\DeltaBundler\traverseDependencies.js:396:18)
    at D:\PR-BBX_Projects\BookBoxApp\node_modules\metro\src\DeltaBundler\traverseDependencies.js:269:33
 DELTA  [android, dev] ..\..\../index.js ▓▓▓▓▓░░░░░░░░░░░ 35.4% (631/1105), failed.`
 
 How do I go about fixing this?

**Comment by JeremyDolle** [comment]
Please let me know if the file `App/Config/index.js` exists. If yes try to close the metro bundle and restart it using `yarn start --reset-cache`

**Comment by arvind-bookbox** [comment]
Hi,
As per your advice, I have copied the index.staging.js as index.js in that location App/Config/index.js.
Index.js has the following lines.
`export const Config = {
  API_URL: 'https://jsonplaceholder.typicode.com/users/',
}
`
And I did start the metro bundler in another cmd window with admin access with yarn as you have told. but it gives the same problem! (multiple times I tried the reset cache command)
One slight improvement is that it fails at 44.4% instead of previous 35.4. ;)
Anything else I'm missing?

**Comment by arvind-bookbox** [comment]
Hello Jeremy, 
any updates on my issue? 
Thanks for your time.

**Comment by JeremyDolle** [comment]
Can you share me your code it will be easier for me.

**Comment by arvind-bookbox** [comment]
By code do you mean the full project directory or a certain .js file like App.js, index.js etc?

**Comment by JeremyDolle** [comment]
Yes the whole project please !

**Comment by arvind-bookbox** [comment]
Sure Jeremy, is there an email to which I can send the link to?

**Comment by JeremyDolle** [comment]
Sure ! Hope we will make it work 😉  j.dolle@thecodingmachine.com
